name: Check For Version Update

on:
  pull_request:
    branches:
      - main

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Needed so that we can fetch full history

      - name: Compare pyproject.toml version with main
        run: |
          echo "Fetching main branch..."
          git fetch origin main

          echo "Extracting version from main branch..."
          MAIN_VERSION=$(git show origin/main:pyproject.toml | grep -E '^version\s*=' | sed 's/.*"//; s/".*//')
          echo "Main version: $MAIN_VERSION"

          echo "Extracting version from PR branch..."
          PR_VERSION=$(grep -E '^version\s*=' pyproject.toml | sed 's/.*"//; s/".*//')
          echo "PR version: $PR_VERSION"

          # Compare using sort -V which handles version numbers correctly
          lowest=$(echo -e "$MAIN_VERSION\n$PR_VERSION" | sort -V | head -n1)
          if [ "$lowest" = "$MAIN_VERSION" ] && [ "$MAIN_VERSION" != "$PR_VERSION" ]; then
            echo "PR version is higher than main version."
          else
            echo "Error: PR version must be higher than main version."
            exit 1
          fi
